from snakemake.utils import min_version

min_version("6.7.0")

rule all:
    input:
        "output/CHM1_aln_test_linked-subsampled.bam"

rule append_tags2aln:
    input:
        aln_bam = "data/{sample}_aln_test-subsampled.bam",
        methyl_bam = "data/{sample}_m5_test-subsampled.bam"
    output:
        linked_bam = "output/{sample}_aln_test_linked-subsampled.bam"
    log:
        "logs/scripts/{sample}.log"
    script:
        "scripts/append_linked-tags.py"
